In [2]:
!pip install pandas
!pip install polars

Requirement already satisfied: pandas in /usr/local/python/3.12.1/lib/python3.12/site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python3 -m pip install --upgrade pip
Requirement already satisfied: polars in /usr/local/python/3.12.1/lib/python3.12/site-packages (1.42.1)
Requirement already satisfied: polars-runtime-32==1.42.1 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from polars) (1.42.1)

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python3 -m pip install --upgrade pip

In [3]:
import pandas as pd
import polars as pl

url="https://raw.githubusercontent.com/jbrownlee/Datasets/master/airline-passengers.csv"

data=pd.read_csv(url)
data.head(5)

     Month  Passengers
0  1949-01         112
1  1949-02         118
2  1949-03         132
3  1949-04         129
4  1949-05         121

In [5]:
data.info(verbose=False)

<class 'pandas.DataFrame'>
RangeIndex: 144 entries, 0 to 143
Columns: 2 entries, Month to Passengers
dtypes: int64(1), str(1)
memory usage: 2.4 KB

In [6]:
data.describe()

       Passengers
count  144.000000
mean   280.298611
std    119.966317
min    104.000000
25%    180.000000
50%    265.500000
75%    360.500000
max    622.000000

In [17]:
data.Month.head(10) #1st approach as method

0    1949-01
1    1949-02
2    1949-03
3    1949-04
4    1949-05
5    1949-06
6    1949-07
7    1949-08
8    1949-09
9    1949-10
Name: Month, dtype: str

In [ ]:
data["Month"][:10]  #just like numpy system

0    1949-01
1    1949-02
2    1949-03
3    1949-04
4    1949-05
5    1949-06
6    1949-07
7    1949-08
8    1949-09
9    1949-10
Name: Month, dtype: str

In [20]:
data.value_counts(data["Passengers"]) #how many time each value used in this list

Passengers
229    3
118    2
135    2
148    2
170    2
      ..
622    1
606    1
508    1
390    1
432    1
Name: count, Length: 118, dtype: int64

In [16]:
data.isnull().sum()

Month         0
Passengers    0
dtype: int64